In [68]:
lengths = [5,8,3,10]
a = [torch.IntTensor([1]+[random.randrange(0,30,1) for _ in range(length-2)]+[2]) for length in lengths]
concatenated = torch.concat(a)

In [78]:
from translation_machine.models import common
stops

tensor([ 0,  5, 13, 16, 26])

In [80]:
res = common.divide_into_sublist(concatenated,lengths)

In [81]:
assert all([ bool(torch.all(el0==el1)) for (el0,el1) in zip(a,res)])

In [82]:
res,a

([tensor([ 1, 25,  1, 16,  2], dtype=torch.int32),
  tensor([ 1, 15, 10, 10, 21, 27, 22,  2], dtype=torch.int32),
  tensor([ 1, 15,  2], dtype=torch.int32),
  tensor([ 1, 19, 16, 25,  3, 13, 14, 17,  2,  2], dtype=torch.int32)],
 [tensor([ 1, 25,  1, 16,  2], dtype=torch.int32),
  tensor([ 1, 15, 10, 10, 21, 27, 22,  2], dtype=torch.int32),
  tensor([ 1, 15,  2], dtype=torch.int32),
  tensor([ 1, 19, 16, 25,  3, 13, 14, 17,  2,  2], dtype=torch.int32)])